### ISSUE TITLE
0 width dimension layer not handled properly

### ISSUE THREAD

**Issue by clemtaylor** [mcous/gerber-to-svg#21]
In eagle I normally use 0 width lines to make up the board dimension layer. svgerber does not seem to use the 0 width lines to define the board perimeter so the board dimension seems to be purely bounding box based.

This is a section from eagle:
![image](https://cloud.githubusercontent.com/assets/1316864/9639351/b5c10c8e-5179-11e5-83cd-6b6b3a100dbf.png)

And the same in gerbv:
![image](https://cloud.githubusercontent.com/assets/1316864/9639432/02cb87ca-517a-11e5-8dc5-bc8322a60667.png)

It renders in svgerber as:
![image](https://cloud.githubusercontent.com/assets/1316864/9639388/d49a7f28-5179-11e5-8eb0-520e2f5a4f18.png)

The board outline layer comes up blank in svgerber, unlike the clockblock example.

What is svgerber expecting in the dimension layer?

**Comment by mcous** [comment]
Hi! Can you please open this issue in [svgerber](https://github.com/mcous/svgerber) with a copy of your outline layer if possible? This issue is related to the board builder there; gerber-to-svg is only concerned with individual layer image generation. Also, can you try setting the width of the outline layer to something non-zero and see if that works?

svgerber is expecting a manifold (i.e. no gaps; there's currently no gap filling capability) trace or set of traces with a width that is greater than 0. The width thing is arbitrary, and will be ditched when I find the time to switch svgerber over to using [tracespace/pcb-stackup](https://github.com/tracespace/pcb-stackup).
