### ISSUE TITLE
Use console.log and force synchronous print instead of streaming

### ISSUE THREAD

**Issue by Immortalin** [mcous/gerber-to-svg#44]
Hi, is it possible to use force synchronous `console.log` instead of streaming to `stdout`? I am running it as a subprocess and the async nature is creating a lot of hard-to-debug bugs. It would be awesome if there's a flag that allows you to just console.log everything since it's more predictable and battle tested.

**Comment by mcous** [comment]
What sort of bugs are you running into? Also, are you asking about the API or the CLI?

The streaming aspect was selected because (my) primary usages of this library always involved asynchronously reading a file piece by piece, e.g. as part of a file upload to a server. I agree that having async all this time was a heavy-handed decision, and that part of the design is not likely to survive the next rewrite. However, until that rewrite happens, forcing synchronous output is unfortunately not an available feature.

And not that this helps anything, but in Node calling `console.log` calls `process.stdout.write` under the hood, so you end up writing to a stream no matter what 😃

**Comment by mcous** [comment]
Is there anyway you could put together a more minimal reproduction case? I don't have the time to debug integration with a tool I've never used (although gitea does look cool!). Without something smaller to test, I can't know this isn't a problem with gitea.

You could also try building a minimal CLI that uses console.log instead of process.write and see where that gets you. The API has a callback interface, so you could do whatever you want:

```js
#!/usr/bin/env node
const gerberToSvg = require('gerber-to-svg')

// get file contents or stream from args or stdin somehow...

// convert
gerberToSvg(fileContentsOrStream, options, (error, results) => {
  if (error) {
    console.error(error)
    process.exit(1)
  }

  console.log(results)
  process.exit()
})
```
